name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  
  workflow_dispatch:

jobs:
  run-linters:
    name: Run HTML, CSS, and JS Linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Linting Tools
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard prettier

      - name: Run HTMLHint
        run: |
          if npx htmlhint '**/*.html'; then
            echo "HTML linting completed successfully."
          else
            echo -e "\033[33mHTML linting found issues.\033[0m"
          fi || true

      - name: Run Stylelint
        run: |
          if npx stylelint '**/*.css'; then
            echo "CSS linting completed successfully."
          else
            echo -e "\033[33mCSS linting found issues.\033[0m"
          fi || true

      - name: Run Prettier Check
        run: |
          if npx prettier --check '**/*.{html,css,js}'; then
            echo "Prettier check completed successfully."
          else
            echo -e "\033[33mPrettier found formatting issues.\033[0m"
          fi || true

      - name: Run Prettier Fix
        run: |
          npx prettier --write '**/*.{html,css,js}' || true
