name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  
  workflow_dispatch:

jobs:
  run-linters:
    name: Run HTML, CSS, and JS Linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Linting Tools
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard prettier

      - name: Run HTMLHint
        run: npx htmlhint '**/*.html' || true

      - name: Run Stylelint
        run: npx stylelint '**/*.css' --fix || true

      - name: Run Prettier Check
        run: npx prettier --check '**/*.{html,css,js}' || true

      - name: Run Prettier Fix
        run: npx prettier --write '**/*.{html,css,js}' || true
