name: Lint

on:
  # Trigger the workflow on push or pull request for any branch
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  # manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-linters:
    name: Run HTML, CSS, and JS Linters
    # Use a self-hosted runner instead of GitHub-hosted (ubuntu-latest)
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install Node.js dependencies including linters and formatters
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
