name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  
  workflow_dispatch:

jobs:
  run-linters:
    name: Run HTML, CSS, and JS Linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Set up Node.js version 16
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Linting Tools
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard prettier

      - name: Run HTMLHint
        run: npx htmlhint 'src/**/*.html'

      - name: Run Stylelint
        run: npx stylelint 'src/**/*.css'

      - name: Run Prettier
        run: npx prettier --check 'src/**/*.{html,css,js}'

      - name: Run Prettier Fix
        run: npx prettier --write 'src/**/*.{html,css,js}'
